# terraform/main.tf

terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 2.0.0"
    }
  }
}

# The runner uses the local ~/.kube/config generated by Minikube
provider "kubernetes" {
  config_path = "~/.kube/config"
}

# Deploy the OpenFaaS Function Custom Resource
resource "kubernetes_manifest" "openfaas_function" {
  manifest = {
    "apiVersion" = "openfaas.com/v1"
    "kind"       = "Function"
    "metadata" = {
      "name"      = "tf-nodeinfo"
      "namespace" = "openfaas-fn"
    }
    "spec" = {
      "name"  = "tf-nodeinfo"
      "image" = "functions/nodeinfo:latest"
      "labels" = {
        "com.openfaas.scale.min" = "1"
        "com.openfaas.scale.max" = "3"
      }
    }
  }
}
